version: "3"
services:
  app:
    image: node:14-alpine
    command: yarn dev
    working_dir: /app
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
volumes:
  node_modules:
